language: php
php:
    - 7.3

services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  - docker-compose up -d
  - docker pull php:7.3-cli
  - docker pull php:7.4-cli
  - docker pull php:8.0-cli

install:
  - composer update

script:
  - ./run-tests.sh
